const state={concepts:[],selected:null,query:""};const $=id=>document.getElementById(id);
async function api(path,options){const response=await fetch(path,options);const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");window.clearTimeout(toast.timer);toast.timer=window.setTimeout(()=>el.classList.remove("show"),2600)}
function renderStats(s){const items=[["知识卡",s.concepts_total??"—"],["Verified",s.verified??"—"],["Draft",s.drafts??"—"],["平均分",s.avg_score??"—"],["反馈事件",s.feedback_events??"—"]];$("stats").innerHTML=items.map(([l,v])=>`<div class="stat"><span class="stat-label">${l}</span><strong class="stat-value">${v}</strong></div>`).join("");$("activity").textContent=(s.latest_log||[]).join("\n")||"暂无运行日志";$("lastUpdated").textContent=`更新于 ${new Date().toLocaleTimeString()}`}
function renderList(cs){const list=$("cardList");if(!cs.length){list.innerHTML='<div class="empty-list">没有匹配的知识卡</div>';return}list.innerHTML=cs.map(c=>{const active=state.selected&&state.selected.name===c.name?" active":"";const st=c.status==="verified"?"verified":"draft";return `<button class="card-item${active}" data-name="${escapeHtml(c.name)}"><div class="card-title"><span>${escapeHtml(c.title||c.name)}</span><span class="score">${c.score==null?"—":Number(c.score).toFixed(1)}</span></div><div class="card-desc">${escapeHtml(c.description||"暂无描述")}</div><div class="meta-row"><span class="badge ${st}">${st}</span><span>${escapeHtml(c.category||"uncategorized")}</span><span>v${c.version||1}</span></div></button>`}).join("");list.querySelectorAll(".card-item").forEach(el=>el.addEventListener("click",()=>selectConcept(el.dataset.name)))}
function renderSignals(signals){const es=Object.entries(signals||{}).filter(([,v])=>v!=null);if(!es.length)return '<div class="subtle">暂无评分信号</div>';return `<div class="signals">${es.map(([n,v])=>{const pct=Math.max(0,Math.min(100,Number(v)*100));return `<div><div class="signal-label"><span>${escapeHtml(n)}</span><span>${Number(v).toFixed(3)}</span></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div>`}).join("")}</div>`}
function renderDetail(c){$("emptyState").classList.add("hidden");const d=$("detail");d.classList.remove("hidden");const sources=(c.sources||[]).map(s=>`<div class="source">${escapeHtml(s.path||"source")}${s.lines?` · lines ${escapeHtml(String(s.lines))}`:""}${s.pinned?" · pinned":""}</div>`).join("")||'<div class="subtle">暂无来源</div>';d.innerHTML=`<div class="detail-header"><div><div class="detail-title"><h3>${escapeHtml(c.title||c.name)}</h3><span class="badge ${c.status==="verified"?"verified":"draft"}">${escapeHtml(c.status)}</span></div><p class="detail-description">${escapeHtml(c.description||"暂无描述")}</p></div><div class="detail-actions"><button class="button ghost small" data-action="rescore">重新评分</button><button class="button ghost small" data-action="correct">标记需修订</button><button class="button primary small" data-action="rate">有帮助 · 5</button></div></div><div class="section"><div class="section-title">Score / ${c.score==null?"—":Number(c.score).toFixed(1)} · confidence ${c.confidence==null?"—":c.confidence}</div>${renderSignals(c.score_breakdown)}</div><div class="section"><div class="section-title">Sources</div><div class="source-list">${sources}</div></div><div class="section"><div class="section-title">Knowledge body</div><div class="card-body">${escapeHtml(c.body||"")}</div></div>`;d.querySelectorAll("[data-action]").forEach(el=>el.addEventListener("click",()=>handleAction(el.dataset.action,c.name)))}
async function loadStatus(){renderStats(await api("/api/status"))}
async function loadConcepts(){const status=$("statusFilter").value;const query=state.query.trim();let data;if(query){data=await api(`/api/query?q=${encodeURIComponent(query)}&top=50${status?`&status=${encodeURIComponent(status)}`:""}`);state.concepts=data.hits||[];$("searchHint").textContent=`${data.total||0} 个候选 · 搜索不会自动计入 usage`}else{data=await api(`/api/concepts${status?`?status=${encodeURIComponent(status)}`:""}`);state.concepts=data.concepts||[];$("searchHint").textContent="默认显示全部知识卡；搜索不会自动计入 usage。"}renderList(state.concepts)}
async function selectConcept(name){try{const data=await api(`/api/concepts/${encodeURIComponent(name)}`);state.selected=data.concept;renderList(state.concepts);renderDetail(state.selected)}catch(e){toast(e.message)}}
async function handleAction(action,name){try{if(action==="rescore"){const data=await api("/api/rescore",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});toast(`重新评分：${data.report.score} · ${data.report.gate}`);await refresh(name);return}const payload=action==="rate"?{name,action:"rate",rating:5}:{name,action:"correct"};await api("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});toast(action==="rate"?"已记录有帮助":"已记录需修订");await refresh(name)}catch(e){toast(e.message)}}
async function refresh(name){await Promise.all([loadStatus(),loadConcepts()]);if(name)await selectConcept(name)}
async function scan(){try{const d=await api("/api/scan");toast(`liveMode 扫描：${d.total||0} 个候选`);$("activity").textContent=`发现 ${d.total||0} 个候选文件\n`+(d.candidates||[]).map(c=>c.path).join("\n")}catch(e){toast(e.message)}}
function escapeHtml(value){return String(value==null?"":value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
async function boot(){$("refreshBtn").addEventListener("click",()=>refresh(state.selected&&state.selected.name));$("scanBtn").addEventListener("click",scan);$("statusFilter").addEventListener("change",()=>refresh(state.selected&&state.selected.name));$("searchForm").addEventListener("submit",e=>{e.preventDefault();state.query=$("queryInput").value;refresh()});try{await refresh()}catch(e){$("activity").textContent=`无法连接 runner：${e.message}`}window.setInterval(()=>loadStatus().catch(()=>{}),30000)}boot();
